services:
  app:
    build: .
    # volumes:
      # You might need to create this directory with correct permissions first
      # Run: mkdir -p ./data && chmod 777 ./data
      # - ./data:/app/data
    environment:
      - ACTUAL_SERVER_URL=${ACTUAL_SERVER_URL}
      - ACTUAL_SERVER_PASSWORD=${ACTUAL_SERVER_PASSWORD}
      - ACTUAL_SYNC_ID=${ACTUAL_SYNC_ID}
      # - ACTUAL_DATA_DIR=/app/data  # You can override the data directory if needed
      - MONO_TOKEN=${MONO_TOKEN}
      - ACCOUNT_IDS=${ACCOUNT_IDS}
      # Lookback period in ISO8601 duration format (default: P6M = 6 months)
      # - LOOKBACK_PERIOD=P6M
      - CRON=*/30 * * * *  # Run every 30 minutes
      # - CRON_SENTRY_DSN=https://public@sentry.example.com/1
    restart: unless-stopped
